{{- if and (.Values.enterprise).enabled (.Values.auditLog).enabled }}
{{- if not .Values.auditLog.maintenance.existingSecret }}
{{- if and .Values.auditLog.maintenance.accessKeyID .Values.auditLog.maintenance.secretAccessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "audit.fullname" . }}
  labels:
    {{- include "audit.labels" . | nindent 4 }}
type: Opaque
data:
  access_key_id: {{ .Values.auditLog.maintenance.accessKeyID | b64enc }}
  secret_access_key: {{ .Values.auditLog.maintenance.secretAccessKey | b64enc }}
{{- end }}
{{- end }}
{{- end }}
