{{- if include "iqs.enabled" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iqs.fullname" . }}
  labels:
    {{- include "iqs.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "iqs.selectorLabels" . | nindent 4 }}
{{- end }}
