{{- if .Values.mds.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "arktika.fullname" . }}
  labels:
    {{- include "arktika.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "arktika.selectorLabels" . | nindent 4 }}
{{- end }} 