
# TODO(add as option to additionalResources)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb
  labels:
    app: dynamodb-local
    component: dynamodb
spec:
  replicas: 1
  selector:
    matchLabels:
      component: dynamodb
      app: dynamodb-local
  template:
    metadata:
      labels:
        component: dynamodb
        app: dynamodb-local
    spec:
      containers:
      - image: amazon/dynamodb-local:1.20.0
        args: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
        imagePullPolicy: Always
        name: dynamodb
        ports:
        - containerPort: 8000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb-service
  labels:
    app: dynamodb-local
    component: dynamodb
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: dynamo
  selector:
    app: dynamodb-local
    component: dynamodb