{{- if (.Values.fluffy).enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fluffy.fullname" . }}
  labels:
    {{- include "fluffy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.fluffy.replicaCount }}
  selector:
    matchLabels:
      {{- include "fluffy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/fluffy-configmap.yaml") . | sha256sum }}
      {{- with .Values.fluffy.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fluffy.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.fluffy.image.privateRegistry.enabled }}
      imagePullSecrets:
        {{- if .Values.fluffy.image.privateRegistry.secretToken }}
        - name: "docker-registry"
        {{- else }}
        - name: {{ .Values.fluffy.image.privateRegistry.secretName }}
        {{- end }}
      {{- end }}
      serviceAccountName: {{ include "fluffy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
            - run
          {{ range (.Values.fluffy).additionalArguments }}
            - {{ . }}
          {{ end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.fluffy.image.repository }}:{{ .Values.fluffy.image.tag }}"
          imagePullPolicy: {{ .Values.fluffy.image.pullPolicy }}
          ports:
            - name: http-sso
              containerPort: {{ include "fluffy.sso.containerPort" . }}
              protocol: TCP
            - name: http-rbac
              containerPort: {{ include "fluffy.rbac.containerPort" . }}
              protocol: TCP
          readinessProbe:
            {{- if  ((.Values.readinessProbe).failureThreshold) }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            {{-  end }}
            {{- if  ((.Values.readinessProbe).periodSeconds) }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            {{-  end }}
            {{- if  ((.Values.readinessProbe).successThreshold) }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            {{-  end }}
            {{- if  ((.Values.readinessProbe).timeoutSeconds) }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            {{-  end }}   
            httpGet:
              path: /_health
              port: http-sso
          livenessProbe:
            {{- if  ((.Values.livenessProbe).failureThreshold) }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            {{-  end }}
            {{- if  ((.Values.livenessProbe).periodSeconds) }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            {{-  end }}
            {{- if  ((.Values.livenessProbe).successThreshold) }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            {{-  end }}
            {{- if  ((.Values.livenessProbe).timeoutSeconds) }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            {{-  end }}     
            {{- if  ((.Values.livenessProbe).initialDelaySeconds) }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            {{-  end }}                                                
            httpGet:
              path: /_health
              port: http-sso
          resources:
            {{- toYaml .Values.fluffy.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.fluffy.extraVolumeMounts }}
            {{ toYaml .Values.fluffy.extraVolumeMounts | nindent 12 }}
          {{- end }}
            - name: {{ include "fluffy.fullname" . }}-config
              mountPath: /etc/fluffy/
          {{- if and .Values.fluffy.sso.enabled (.Values.fluffy.sso.saml).enabled }}
            - name: secret-volume
              readOnly: true
              mountPath: /etc/saml_certs/
          {{- end }}
          {{- include "fluffy.env" . | nindent 10 }}
      volumes:
        {{- include "fluffy.volumes" . | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end}}
