{{- if (.Values.fluffy).enabled }}
{{- if (.Values.fluffy.secrets).create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fluffy.fullname" . }}
  labels:
    {{- include "fluffy.labels" . | nindent 4 }}
type: Opaque
data:
# TODO(isan) this is not a common secret anymore consider making dedicated to sso no point in this condition
{{- if and .Values.fluffy.sso.enabled (.Values.sso.oidc).client_secret }}
  oidc_client_secret: {{ .Values.sso.oidc.client_secret | b64enc }}
{{- end}}
{{- end}}

---
# docker-registry secret for image pull

{{- if and .Values.image.privateRegistry.enabled .Values.image.privateRegistry.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.image.privateRegistry.config | toJson | b64enc }}
{{- end }}

---
# certificates to use with SAML SSO against server such as AD FS

{{- if and (.Values.sso).enabled (.Values.sso.saml).enabled }}
{{- if .Values.sso.saml.certificate.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: saml-certificates
data:
  rsa_saml_public.pem: '{{ .Values.sso.saml.certificate.saml_rsa_public_cert | b64enc }}'
  rsa_saml_private.cert: '{{ .Values.sso.saml.certificate.saml_rsa_private_key | b64enc }}'
{{- end }}
{{- end }}

{{- end}}