{{- if and (.Values.secrets) (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lakefs.fullname" . }}
  labels:
    {{- include "lakefs.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.secrets.databaseConnectionString }}
  database_connection_string: {{ .Values.secrets.databaseConnectionString | default "" | b64enc }}
{{- end }}
{{- if .Values.secrets.authEncryptSecretKey }}
  auth_encrypt_secret_key: {{ .Values.secrets.authEncryptSecretKey | default "" | b64enc }}
{{- end }}
{{- if .Values.auth.oidc.clientSecret }}
  oidc_client_secret: {{ .Values.auth.oidc.clientSecret | b64enc }}
{{- end}}
{{- if .Values.auth.ldap.bindPassword }}
  ldap_bind_password: {{ .Values.auth.ldap.bindPassword | b64enc }}
{{- end}}
{{- end }}
---

# certificates to use with SAML SSO against server such as AD FS

{{- if .Values.auth.saml.enabled }}
{{- if .Values.auth.saml.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: saml-certificates
data:
  rsa_saml_public.pem: '{{ .Values.auth.saml.certificate.saml_rsa_public_cert | b64enc }}'
  rsa_saml_private.key: '{{ .Values.auth.saml.certificate.saml_rsa_private_key | b64enc }}'
{{- end }}
{{- end }}
