{{- if and (.Values.secrets) (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lakefs.fullname" . }}
  labels:
    {{- include "lakefs.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.secrets.databaseConnectionString }}
  database_connection_string: {{ .Values.secrets.databaseConnectionString | default "" | b64enc }}
{{- end }}
{{- if .Values.secrets.authEncryptSecretKey }}
  auth_encrypt_secret_key: {{ .Values.secrets.authEncryptSecretKey | default "" | b64enc }}
{{- end }}
{{- end }}
