{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lakefs.fullname" . }}
  labels:
    {{- include "lakefs.labels" . | nindent 4 }}
type: Opaque
data:
{{- if (.Values.secrets).databaseConnectionString }}
  database_connection_string: {{ .Values.secrets.databaseConnectionString | default "" | b64enc }}
{{- end }}
{{- if (.Values.secrets).authEncryptSecretKey }}
  auth_encrypt_secret_key: {{ .Values.secrets.authEncryptSecretKey | default "" | b64enc }}
{{- end }}

{{- if (.Values.enterprise).enabled }}

{{- if .Values.secrets.licenseContents }}
  license_contents: {{ .Values.secrets.licenseContents | default "" | b64enc }}
{{- end }}

{{- if (((.Values.enterprise).auth).ldap).enabled }}
{{- if (((.Values.enterprise).auth).ldap).bindPassword }}
  # LDAP bind password secret, used for LDAP authentication
  ldap_bind_password: {{ .Values.enterprise.auth.ldap.bindPassword | b64enc }}
{{- end }}
{{- end }}
{{- if (((.Values.enterprise).auth).oidc).enabled }}
{{- if (((.Values.enterprise).auth).oidc).clientSecret }}
# OIDC client secret, used for OIDC authentication
  oidc_client_secret: {{ .Values.enterprise.auth.oidc.clientSecret | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
---

# certificates to use with SAML SSO against server such as AD FS

{{- if (.Values.enterprise).enabled }}
{{- if (((.Values.enterprise).auth).saml).enabled }}
{{- if (((.Values.enterprise).auth).saml).createCertificateSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: saml-certificates
data:
  rsa_saml_public.pem: '{{ .Values.enterprise.auth.saml.certificate.samlRsaPublicCert | b64enc }}'
  rsa_saml_private.key: '{{ .Values.enterprise.auth.saml.certificate.samlRsaPrivateKey | b64enc }}'
{{- end }}
{{- end }}
{{- end }}
---
{{- if and .Values.image.privateRegistry.enabled .Values.image.privateRegistry.secretToken }}
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "lakefs.dockerConfigJson" . }}
{{- end }}